services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../TestbenchConfigs:/configs
    command: [ "--config-root", "/configs" ]
    restart: unless-stopped
  # tunnel:
  #   image: cloudflare/cloudflared:latest
  #   restart: unless-stopped
  #   secrets:
  #     - cloudflare_token
  #   environment:
  #     - TUNNEL_TOKEN_FILE=/run/secrets/cloudflare_token
  #   command: tunnel --no-autoupdate run
  #   depends_on:
  #     - app

secrets:
  cloudflare_token:
    file: cloudflared.secret
