# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - TestbenchManager-dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: testbenchmanager-dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH for private Git deps
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EPCOMMS_DEPLOY_KEY }}

      - name: Add github.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: üè∑Ô∏è Determine Image Tags
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     tags: |
      #       type=raw,value=latest,enable={{isSourceBranch 'main'}}
      #       type=ref,event=tag

      - name: üì¶ Build and Push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Pass the PAT securely for the private dependency pull (HTTPS method)
          build-args: |
            GITHUB_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
      

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   permissions:
  #     id-token: write #This is required for requesting the JWT
  #     contents: read #This is required for actions/checkout

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: python-app
      
  #     - name: Login to Azure
  #       uses: azure/login@v2
  #       with:
  #         client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E4062A7E4B444655861A190456013C80 }}
  #         tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_22E475E56B2A40BABA3E0E0B68E5A727 }}
  #         subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AC79DC4B834A4044B59E9DDF113BBCDB }}

  #     - name: 'Deploy to Azure Web App'
  #       uses: azure/webapps-deploy@v3
  #       id: deploy-to-webapp
  #       with:
  #         app-name: 'TestbenchManager-dev'
  #         slot-name: 'Production'
          